### ISSUE TITLE
Sourcemaps generating wrong names with multiple css files

### ISSUE THREAD

**Issue by xipheCom** [cssnext/gulp-cssnext#3]
If we have two files in css, let's say a.css and b.css and want create a sourcemap we see the wrong origin name in browser debugging tools like chrome, firefox, etc.
Code:
```javascript
gulp.task("cssmaps", function () {
  return gulp.src("css/*.css", {base: "."})
          .pipe(cssnext({sourcemap: true}))
          .pipe(rename({suffix: '.min'}))
          .pipe(gulp.dest("."));
});
```
will create a.min.css with a sourcemap which refers to a.css and b.min.css with a sourcemap which also refers to a.css instead of b.css.

I think it has something to do with side effects in 
```javascript
        options.from = options.from === undefined ? (file.path !== null ? file.path : undefined) : options.from
        transformed = cssnext(contents, options)
```
we should make a copy of the options object or set it to undefined after we used it after the first+ time
Here is the undefined solution which will generate correct names in the sourcemaps
```javascript
        options.from = options.from === undefined ? (file.path !== null ? file.path : undefined) : options.from
        transformed = cssnext(contents, options)
        options.from = undefined
```

**Comment by bloodyowl** [comment]
I'd rather like we do a copy of the object.
do you want to PR this? I'll handle it otherwise

**Comment by xipheCom** [comment]
Well, it was a (quick) suggestion because i need it. Of course a deep copy of the object would be the best solution. Go ahead.

**Comment by MoOx** [comment]
Since we only are adding one prop, I thing using object.assign will do the job here

**Comment by MoOx** [comment]
I think will 1.0.1 fix this issue

**Comment by MoOx** [comment]
I guess this is fixed. Feel free to reopen if still relevant.
