### ISSUE TITLE
Use PostCSS async API

### ISSUE THREAD

**Issue by ai** [cssnext/gulp-cssnext#8]
New version `postcss-import` uses async API, so sync code `transformed = cssnext(contents, options)` can’t work anymore.

Here is a error report: https://github.com/postcss/postcss/issues/412#issuecomment-119299635

This is why [PostCSS Runner Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md) has “2.2. Use only the asynchronous API” rule.

/cc @MoOx

**Comment by ctaymor** [comment]
Working on a pull request
/cc @gpleiss

**Comment by MoOx** [comment]
I think I am going to revert the change in postcss-import change since it will break too many things right now. I think a pull request is not that simple because it's breaking all cssnext usage.

**Comment by ai** [comment]
@ctaymor awesome! If you have a time, please take a look at other Runner Guidelines rules. They are very important only because they cause big problems in long-term perspective.

**Comment by ctaymor** [comment]
@MoOx Okay, great.

**Comment by MoOx** [comment]
Like I said, please don't waste your time. It's a big issue related to postcss-import that didn't respect semver, so let me fix that.
Meanwhile: https://github.com/postcss/postcss/issues/412#issuecomment-119307729
